### ISSUE TITLE
2.0.0/2.0.1  use WaitLatch incorrectly,  which can cause coredump

### ISSUE THREAD

**Issue by anjingde** [greenplum-db/diskquota#263]
PG_FUNCTION_INFO_V1(wait_for_worker_new_epoch);
Datum
wait_for_worker_new_epoch(PG_FUNCTION_ARGS)
{
	TimestampTz start_time    = GetCurrentTimestamp();
	uint32      current_epoch = worker_get_epoch(MyDatabaseId);
	for (;;)
	{
		CHECK_FOR_INTERRUPTS();
		if (check_for_timeout(start_time)) start_time = GetCurrentTimestamp();
		uint32 new_epoch = worker_get_epoch(MyDatabaseId);
		/* Unsigned integer underflow is OK */
		if (new_epoch - current_epoch >= 2u)
		{
			PG_RETURN_BOOL(true);
		}
		/* Sleep for naptime to reduce CPU usage */
		(void)WaitLatch(&MyProc->procLatch, WL_LATCH_SET | WL_TIMEOUT, diskquota_naptime ? diskquota_naptime : 1);
		ResetLatch(&MyProc->procLatch);
	}
	PG_RETURN_BOOL(false);
}

 this is correct

(void)WaitLatch(&MyProc->procLatch, WL_LATCH_SET | WL_TIMEOUT | WL_POSTMASTER_DEATH, diskquota_naptime ? diskquota_naptime : 1);

**Comment by higuoxing** [comment]
Hi @anjingde, thanks for your reporting and fix. Could you please share more context with us?

1. Which process is temrinated abnormally? The Greenplum server or diskquota worker?
2. Could you please share the coredump file so that we can debug it?

**Comment by anjingde** [comment]
@higuoxing  coredump 
0  0x00007fb90e147387 in raise () from /lib64/libc.so.6
#1  0x00007fb90e148a78 in abort () from /lib64/libc.so.6
#2  0x0000000000ce1ed3 in ExceptionalCondition (
    conditionName=conditionName@entry=0x1404288 "!(!IsUnderPostmaster || (wakeEvents & (1 << 5)) || (wakeEvents & (1 << 4)))",
    errorType=errorType@entry=0x121500b "FailedAssertion", fileName=fileName@entry=0x1403de0 "latch.c",
    lineNumber=lineNumber@entry=388) at assert.c:40
#3  0x0000000000b736e1 in WaitLatchOrSocket (latch=0x7fb8ef8098a4, wakeEvents=9, wakeEvents@entry=25, sock=sock@entry=-1,
    timeout=2, wait_event_info=wait_event_info@entry=184549376) at latch.c:388
#4  0x0000000000b73700 in WaitLatch (latch=<optimized out>, wakeEvents=wakeEvents@entry=25, timeout=<optimized out>,
    wait_event_info=wait_event_info@entry=184549376) at latch.c:348
#5  0x00007fb903c41999 in wait_for_worker_new_epoch (fcinfo=<optimized out>) at diskquota.c:1379
#6  0x00000000009ac7e4 in ExecInterpExpr (state=0x77b11c0, econtext=0x77b0eb0, isnull=<optimized out>) at execExprInterp.c:635
#7  0x00000000009ebd67 in ExecEvalExprSwitchContext (isNull=0x7fff76af98df, econtext=0x77b0eb0, state=0x77b11c0)
    at ../../../src/include/executor/executor.h:353
#8  ExecProject (projInfo=0x77b11b8) at ../../../src/include/executor/executor.h:387
#9  ExecResult (pstate=0x77b0d98) at nodeResult.c:157
#10 0x00000000009babf5 in ExecProcNodeGPDB (node=0x77b0d98) at execProcnode.c:629
#11 0x00000000009b12ba in ExecProcNode (node=0x77b0d98) at ../../../src/include/executor/executor.h:268
#12 ExecutePlan (estate=0x77b0a90, planstate=0x77b0d98, use_parallel_mode=<optimized out>, operation=CMD_SELECT,
    sendTuples=true, numberTuples=0, direction=ForwardScanDirection, dest=0x75e0528, execute_once=true) at execMain.c:2714
#13 0x00000000009b1be1 in ExecutePlan (execute_once=true, dest=0x75e0528, direction=ForwardScanDirection, numberTuples=0,
    sendTuples=true, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate

**Comment by higuoxing** [comment]
> 

Oh, I got it. It seems that you are compiling diskquota against Greenplum 7 (https://github.com/greenplum-db/gpdb/tree/main). Currently, this extension only supports Greenplum 6 (https://github.com/greenplum-db/gpdb/tree/6X_STABLE).

We are working on porting it to Greenplum 7. Did you meet any other issues except this one? We can address them all.

**Comment by anjingde** [comment]
thank you!

**Comment by beeender** [comment]
GPDB7 support has been done. I am closing this issue.

@anjingde feel free to reopen this if needed.
