### ISSUE TITLE
Disk qouta worker infinitely waits network.  

### ISSUE THREAD

**Issue by reshke** [greenplum-db/diskquota#365]
Hi hackers!

Recently we faces problem with one of our Greenplum production cluster. The problem was that diskqouta worker stuck, waiting some messages from network, while holding locks on relations

```
postgres=# select * from pg_locks where relation=57129168;
 locktype | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction |   pid   |           mode           | granted | fastpath | mppsessionid | mpp
iswriter | gp_segment_id
----------+----------+----------+------+-------+------------+---------------+---------+-------+----------+--------------------+---------+--------------------------+---------+----------+--------------+----
---------+---------------
 relation |  2066355 | 57129168 |      |       |            |               |         |       |          | 7/1474366          | 3820814 | ShareUpdateExclusiveLock | f       | f        |      6982934 | t
         |            -1
 relation |  2066355 | 57129168 |      |       |            |               |         |       |          | 3/73604            |    6007 | RowExclusiveLock         | t       | f        |      3374601 | t
         |            -1
 relation |  2066355 | 57129168 |      |       |            |               |         |       |          | 3/73604            |    6007 | ExclusiveLock            | t       | f        |      3374601 | t
         |            -1
 relation |  2066355 | 57129168 |      |       |            |               |         |       |          | 13/39282           | 1732059 | RowExclusiveLock         | t       | f        |      3374601 | t
         |             0
 relation |  2066355 | 57129168 |      |       |            |               |         |       |          | 47/195657          | 1732144 | RowExclusiveLock         | t       | f        |      3374601 | t
         |             1
 relation |  2066355 | 57129168 |      |       |            |               |         |       |          | 16/255405          | 1732062 | RowExclusiveLock         | t       | f        |      3374601 | t
         |             2
 relation |  2066355 | 57129168 |      |       |            |               |         |       |          | 39/181183          | 1732143 | RowExclusiveLock         | t       | f        |      3374601 | t
         |             3
 relation |  2066355 | 57129168 |      |       |            |               |         |       |          | 19/445630          | 1732061 | RowExclusiveLock         | t       | f        |      3374601 | t
         |             4

```
 This causes `analyze diskquota.table_size` command to stuck.
Here is backtrace: 
```
root@<cut>~ # bt -p 6007
[New LWP 6008]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x0000560abab2e8c7 in pq_set_nonblocking (nonblocking=nonblocking@entry=0 '\000') at pqcomm.c:892
#0  0x0000560abab2e8c7 in pq_set_nonblocking (nonblocking=nonblocking@entry=0 '\000') at pqcomm.c:892
#1  0x0000560abab2ecd3 in internal_putbytes (s=s@entry=0x7fff4d68dc0c "N\177", len=len@entry=1) at pqcomm.c:1484
#2  0x0000560abab30566 in pq_putmessage (msgtype=<optimized out>, s=0x560af7d7f448 "WARNING:  checkNetworkTimeout: interconnect may encountered a network error, please check your network  (seg105 slice1 10.192.1.67:6003 pid=1227791)\n", len=150) at pqcomm.c:1715
#3  0x0000560abab3122c in pq_endmessage (buf=buf@entry=0x7fff4d68dca0) at pqformat.c:347
#4  0x0000560abadf511d in forwardQENotices () at cdbconn.c:850
#5  0x0000560abadf66d9 in processResults (dispatchResult=dispatchResult@entry=0x560abd204338) at cdbdisp_async.c:1138
#6  0x0000560abadf75b8 in handlePollSuccess (fds=<optimized out>, pParms=<optimized out>) at cdbdisp_async.c:825
#7  checkDispatchResult (ds=0x560abcbd0b88, timeout_sec=-1) at cdbdisp_async.c:638
#8  0x0000560abadf54ae in cdbdisp_checkDispatchResult (ds=ds@entry=0x560abcbd0b88, waitMode=<optimized out>) at cdbdisp.c:133
#9  0x0000560abaae57b6 in mppExecutorFinishup (queryDesc=queryDesc@entry=0x560af6bae108) at execUtils.c:2237
#10 0x0000560abaad18c3 in standard_ExecutorEnd (queryDesc=0x560af6bae108) at execMain.c:1329
#11 0x0000560abab0af09 in _SPI_pquery (queryDesc=queryDesc@entry=0x560af6bae108, tcount=tcount@entry=0, fire_triggers=1 '\001') at spi.c:2650
#12 0x0000560abab0cfc3 in _SPI_execute_plan (plan=plan@entry=0x7fff4d68e540, paramLI=paramLI@entry=0x0, snapshot=snapshot@entry=0x0, crosscheck_snapshot=crosscheck_snapshot@entry=0x0, read_only=read_only@entry=0 '\000', fire_triggers=fire_triggers@entry=1 '\001', tcount=0) at spi.c:2321
#13 0x0000560abab0d2f3 in SPI_execute (src=0x560abcf5a2a8 "insert into diskquota.table_size values (141000603,268173312,61), (139931822,553368,134), (140985200,813920,104), (139915756,793960,99), (140967746,2125696,48), (140970111,1121832,96), (139930318,6289"..., read_only=<optimized out>, tcount=0) at spi.c:436
#14 0x00007f7d10b8effa in ?? () from /opt/greenplum-db-6/lib/postgresql/diskquota-2.0.so
#15 0x00007f7d10b87817 in disk_quota_worker_main () from /opt/greenplum-db-6/lib/postgresql/diskquota-2.0.so
#16 0x0000560ababe45f6 in StartBackgroundWorker () at bgworker.c:753
#17 0x0000560ababf0fc3 in do_start_bgworker (rw=0x560abca067e0) at postmaster.c:6142
#18 maybe_start_bgworker () at postmaster.c:6387
#19 0x0000560ababf2305 in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster.c:5564
#20 <signal handler called>
#21 0x00007f7d17cd1cd7 in __GI___select (nfds=nfds@entry=8, readfds=readfds@entry=0x7fff4d68fdd0, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7fff4d68fd30) at ../sysdeps/unix/sysv/linux/select.c:41
#22 0x0000560aba8edbc2 in ServerLoop () at postmaster.c:1900
#23 0x0000560ababf3ce7 in PostmasterMain (argc=6, argv=0x560abc99a990) at postmaster.c:1526
#24 0x0000560aba8f0147 in main (argc=6, argv=0x560abc99a990) at main.c:245
```

Also `select pg_terminate_backend(6007);`  does not kill the process. Restart of Greenplum does:)
How this can be fixed? Is this some sort of bug?

**Comment by zhrt123** [comment]
Hello, this error is caused by the wrong way that we use the bgworker. It is fixed by this PR #314

**Comment by zhrt123** [comment]
Could we close this issue if there is no other problem?

**Comment by reshke** [comment]
sure
